### ISSUE TITLE
Support a full-screen mode (without the TV frame)

### ISSUE THREAD

**Issue by zshall** [zshall/program-guide#28]
The site should have an alternate display mode where the TV mask is gone and it displays fullscreen, whether that be in 4:3 or 16:9. Scanlines will be gone and the sides of the 4:3 will be black.

This is a useful feature if you want to display the site on a real TV and don't need a picture of the TV.

The controls will be hidden and a keyboard interface will be necessary to control the TV or escape from this mode back to the frame view.

**Comment by zshall** [comment]
![abe7a972-dc18-45e9-b327-a83fd1f9ec56](https://user-images.githubusercontent.com/175742/47404388-1e76ef80-d71b-11e8-9b45-ee0820e27b29.jpeg)

When there’s no TV skin, moving the mouse or tapping the screen should bring up an overlay with links to toggle full screen mode, the TV skin, screen filters, and mute. Options for channel and volume controls should be on there too.

**Comment by alexdresko** [comment]
What are the use cases for watching without a skin?

**Comment by alexdresko** [comment]
Or full screen for that matter.

**Comment by DDroid** [comment]
Well @alexdresko I would say post production proposes or for just for the pleasure of viewing full screen (haha I know, I'm captain obvious)

**Comment by zshall** [comment]
New CSS is needed to make this happen. When I wrote the original CSS, I didn’t use a grid system. Everything in the app is absolutely positioned and scaled up and down when the window is resized. This was adequate for the original scope of the project but I didn’t know as much about viewport units or CSS grid. A new version must be made that scales at any screen size that takes advantage of these features.

**Comment by zshall** [comment]
Implemented in version 2. We utilize new `@container` queries in recent CSS improvements to dynamically scale HTML at any size. We'll be using a 4:3 aspect ratio at 640x480px and scale up or down depending on monitor resolution.
