### ISSUE TITLE
Table headers are too tall in Chromium

### ISSUE THREAD

**Issue by zshall** [zshall/program-guide#36]
Table headers for the guide are taking up too much space on the page. This bug doesn't appear on Safari on iOS, so it appears to be browser-specific.

![image](https://user-images.githubusercontent.com/175742/140951511-da8d223d-fddd-4c15-b238-96c1aa95e1e1.png)

This bug appears to be fixed by removing the `height` rule for the table itself:

![image](https://user-images.githubusercontent.com/175742/140952308-89e2d153-0231-4764-92d8-9ffe7538f1fd.png)

**Comment by doomcup** [comment]
Can confirm this is an issue in waterfox, edge, and chrome

**Comment by zshall** [comment]
Merged! CSS and SCSS updated and the site is live now.
