### ISSUE TITLE
Allowing the choice of the the initial version of the Prevue Guide

### ISSUE THREAD

**Issue by chriskewl** [zshall/program-guide#55]
Have you considered having a "theme" that runs like the old Prevue Guide?
[https://www.youtube.com/watch?v=erJpbQbUEp8](https://www.youtube.com/watch?v=erJpbQbUEp8)

I am making a cool video player that is housed inside an old Scientific Atlanta cable box that I want channel 99 to show the guide. Since this is an 80s cablebox I'd love for the EPG to be an 80s one as well.

Thanks!

**Comment by chriskewl** [comment]
That sounds great, I know it is laid out a little different but it really is nostalgic for some people like me. :) Thanks!

**Comment by zshall** [comment]
I've put together the first version of this guide theme in the latest release!

https://github.com/zshall/program-guide/releases/tag/v2.0.0-beta.11-21-2024

**Comment by chriskewl** [comment]
This can be closed, this is great!
